### ISSUE TITLE
CF : check_missing_data

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#12]
Running Compliance Checker on the dataset from: /mnt/ebs/wip/ANMN/timeSeries/new_tb/IMOS_ANMN-WA_TZ_20140925T080000Z_WATR50_FV01_WATR50-1409-TR-1060-496_END-20150522T023000Z_C-20150522T092647Z.nc (actually affects most of ITFTIS_FV01 files)

Checker output:

```
 missing_data                   :2:     0/ 1 : The auxillary coordinates
                                                      do not have the same
                                                      missing data locations,
                                                      The coordinate variables
                                                      do not have the same
                                                      missing data locations as
                                                      the auxillary coordinates

```

which means 

`It is not permitted for auxiliary coordinate variables to have missing values for elements where there is non-missing data.`  if you understand what this means, I wouldn't mind an explanation. See 9.6 chapter

This the case for the  DEPTH AND TEMP variables (in the file mentionned above)

Ncdump output:

```
float DEPTH(TIME) ;
                DEPTH:coordinates = "TIME LATITUDE LONGITUDE NOMINAL_DEPTH DEPTH" ;
                DEPTH:_FillValue = 999999.f ;

...
float TEMP(TIME) ;
                TEMP:coordinates = "TIME LATITUDE LONGITUDE NOMINAL_DEPTH DEPTH" ;
                TEMP:_FillValue = 999999.f ;
```

Both DEPTH and TEMP have a coordinate attribute equals to 'TIME LATITUDE LONGITUDE NOMINAL_DEPTH '. But all these coordinates are missing the `_FillValue` attribute. This seems to be the reason why the checker is failing.

However, DEPTH won't have a coordinate attribute in the future (https://github.com/aodn/compliance-checker/issues/8) so does this solve half of the issue ?

**Comment by mhidas** [comment]
@lbesnard Firstly, you're right, the DEPTH variable here shouldn't have a coordinates attribute, so when that's fixed this check will skip it.

[Here](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/timeSeries/catalog.html?dataset=IMOS/eMII/checker_test/ANMN/timeSeries/IMOS_ANMN-QLD_TZ_20130620T000000Z_ITFTIS_FV01_ITFTIS-1306-SBE56-123_END-20140113T050459Z_C-20150515T020400Z.nc) is a file that only shows this issue for TEMP.

In the case of TEMP, what the checker is saying is that there are points along the timeseries where we have a valid (non-missing) value for TEMP, but one of the corresponding coordinates (as listed in the TEMP:coordinates attribute) has a missing value at that point. This is invalid, because the file is "here's a value of temperature, but I don't know where/when it was measured", i.e. pretty useless!

Looking at the sample file above, this is indeed the case. The variable DEPTH, has ~6000 missing values, while TEMP has none. So this file, and probably most of the others that fail this test, are not CF compliant in this respect.

I see two possible solutions:
  1) We don't report DEPTH as an auxiliary coordinate variable (i.e. remove it from the coordinates attribute of all data variables); or
  2) For any time where DEPTH has a missing value, we set all other coordinate and data values to a _FillValue.

I think I would prefer 1), because otherwise we throw away some potentially useful data just because the pressure sensor was failing. Any thoughts @ggalibert @smancini , others?

**Comment by lbesnard** [comment]
thanks @mhidas , makes more sense now. Many files failed this test. Do you want me to list them all, or it's not really the problem atm

I think 1) is the way to go. However, Shoudn't DEPTH being automatically computed by the toolbox ? I know there's not a PRES variable in this file, but isn't it a pressure sensor on the mooring line. Could the fail actually highlight a real problem with the file ?

**Comment by ggalibert** [comment]
Sometimes, an instrument file without pressure information has a temporal extent greater than the two nearest instrument files with pressure information. In this case, NaNs are introduced in the result of the interpolated DEPTH to possibly pad both ends of the dataset without pressure information.

I'm ok for solution 1).

If DEPTH is not listed as an auxiliary coordinate anymore in the coordinates variable attribute then it could have a coordinate variable attribute itself. @mhidas ?

**Comment by mhidas** [comment]
@lbesnard Yes, in some cases it might highlight a real problem with the file, but I think that's beyond the scope of what we need this checker to do.

@ggalibert Yes, if DEPTH is not itself an auxiliary coordinate var, then it could have a coordinates attribute.

**Comment by ggalibert** [comment]
Modified toolbox accordingly : https://github.com/aodn/imos-toolbox/commit/84b6bf84762587a6afa00ec45b5c9204142fd5d7
