### ISSUE TITLE
CF: unit definition for CDIR variable

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#13]
The CDIR (direction_of_sea_water_velocity) unit attribut is defined as `Degrees clockwise from true North` in an IMOS ADCP file. However, the CF unit for this standard name should be `degree` (also to mention they both use degree and degrees for different direction variables which doesn't seem really consistent)

being CF compliant would lead to information loss in this case. For something such as the direction, it makes a big difference to know which North we're talking about. I can't find any information on this matter on the CF documentation.

Does this mean that we would need a different variable attribute, such as unit_long_name to describe the unit better (or to put the information in the comment attribute) ?

**UPDATE**
similar issue with `platform_yaw_angle` standard name

**Comment by mhidas** [comment]
@lbesnard Yes, according to CF, the units attribute for direction variables needs to be "degree" or equivalent (e.g. "Degrees" is acceptable). The direction and reference point need to be given in other attributes.

This may seem a bit inconvenient, but I guess we do the same thing for depth (e.g. attributes units="m", positive="down", reference = "sea_level"). I haven't seen this done for a direction variable, but it would be the consistent thing to do.

@ggalibert Any thoughts?

**Comment by lbesnard** [comment]
> but I guess we do the same thing for depth (e.g. attributes units="m", positive="down", reference = "sea_level")

so in that case, reference ="true north"

**Comment by ggalibert** [comment]
some measured parameters are vectors/angles with specific directional components :

1- is the direction of the vector to or from?

2- is the angle measured positive clockwise or anti-clockwise?

3- what is the angle referenced to?

The CF FAQ http://cfconventions.org/faq.html#specifying_directions says that this information should be present in the standard names rather than in variable attributes like 'positive'.

The following standard name doesn't answer any of these questions :

**direction_of_sea_water_velocity**
"direction_of_X" means direction of a vector, a bearing. A velocity is a vector quantity.

The following standard name almost answers all questions :

**sea_surface_wave_to_direction**
"to_direction" is used in the construction X_to_direction and indicates **the direction towards which the velocity vector of X is headed**. The direction is a bearing in the usual geographical sense, measured positive **clockwise** from **due north**.

I'm saying "almost" since due north is not strictly accurate. Instead it would be great to find either magnetic north or true north.

**Comment by ggalibert** [comment]
I have contacted the CF metadata mail list http://mailman.cgd.ucar.edu/mailman/listinfo/cf-metadata on this topic.

**Comment by mhidas** [comment]
@ggalibert Thanks for that. Let us know if you get a response.

**Comment by ggalibert** [comment]
At our last netcdf-checker meeting it has been decided we could re-use the variable attributes **positive** and **reference_datum**. 

From CF it looks like although it is not the preferred solution, we may be able to use **positive** for non-vertical coordinates with values other than 'up' or 'down', like 'clockwise' and 'anticlockwise'.

At the moment the IMOS NetCDF Conventions document supports the following values for **reference_datum** :
-geographical coordinates, WGS84 projection
-Mean Sea Level (MSL)
-sea surface
-sea bottom
-sensor

We could add :
-true north
-magnetic north

> a datum is a reference point, surface, or axis on an object against which measurements are made.

**Comment by mhidas** [comment]
@ggalibert I think that would be a reasonable solution, at least until CF respond to the issue. So to summarise, for any variable that is a direction in the horizontal plane, we will have three attributes:

```
units = "degree"
positive = "clockwise"
reference_datum = "true North"
```

Regarding your comment about "to" or "from" directions, I think this is only potentially ambiguous for a _process_ like wind or waves, because their directions can reasonably be described in both ways. In contrast a _vector_ property like velocity or even a compass heading can be thought of as an arrow, and I think "to" is the only one that makes sense.

**Comment by ggalibert** [comment]
The following commit in the toolbox repo addresses this issue : https://github.com/aodn/imos-toolbox/commit/18e6b98fdb62b14e2a853253ceb8492599a0f26f
