### ISSUE TITLE
CF: check_units dimensionless Turbidity

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#7]
Turbidity unit in ANMN file is "NTU" ( specific to an instrument). The CF convention is looking for a unit equal to "1" instead.

```
units                                  :3:     8/ 9 :  
    TURB                               :3:     0/ 1 :  
        known                          :3:     0/ 1 : unknown units type (NTU)
```

/mnt/ebs/wip/ANMN/timeSeries/new_tb/IMOS_ANMN-NRS_CKOSTUZ_20120825T054709Z_NRSDAR_FV01_NRSDAR-1208-Surface-WQM-1_END-20121209T014808Z_C-20150324T034821Z.nc

**Comment by mhidas** [comment]
[THREDDS link](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ANMN/timeSeries/catalog.html?dataset=IMOS/eMII/checker_test/ANMN/timeSeries/IMOS_ANMN-NRS_CKOSTUZ_20120825T054709Z_NRSDAR_FV01_NRSDAR-1208-Surface-WQM-1_END-20121209T014808Z_C-20150324T034821Z.nc) to the exsample file.

According to the [CF standard name table v28](http://cfconventions.org/Data/cf-standard-names/28/build/cf-standard-name-table.html), the canonical unit for _sea_water_turbidity_ is "1", and it seems UDUNITS doesn't recognise "NTU".

This will need to be fixed in the Toolbox @ggalibert

**Comment by ggalibert** [comment]
Fixed : https://github.com/aodn/imos-toolbox/commit/6b41b75df685f35af1b6d16e534e80b784943a2b

**Comment by lbesnard** [comment]
being CF compliant is a good thing, however following the convention can lead to information loss. In this case, I have the feeling keeping NTU somewhere in the file can be valuable to someone.

I've stumbled on another case which is with the `direction_of_sea_water_velocity` standard_name. The unit described in an ADCP file is `Degrees clockwise from true North` but CF only wants `degrees`. However for something such as the direction, it makes a big difference to know which North we're talking about. I can't find any information on this matter on the CF documentation.
Being CF in this case would not be really amazing. Does this mean that we would need a different variable attribute, such as `unit_long_name` to describe the unit better? (same for NTU then)

@smancini @mhidas  @ggalibert  ?

**Comment by ggalibert** [comment]
@lbesnard , I don't think the NTU issue you're raising is comparable to the true north one. Look at the definition of sea_water_turbidity CF standard_name, they mention NTU.

**Comment by lbesnard** [comment]
@ggalibert  fair enough, I'll close this one back and put it  into a new issue
